// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodMvLgjcKIlDH3qS7rJ-lrirW65NbN40',
    appId: '1:269333681612:web:f183798ec29976d274f969',
    messagingSenderId: '269333681612',
    projectId: 'woundcare-fyp',
    authDomain: 'woundcare-fyp.firebaseapp.com',
    storageBucket: 'woundcare-fyp.firebasestorage.app',
    measurementId: 'G-JVL7J36NSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCdSruyt10jC2Bj764CVX7ZDG2IH3Dp8',
    appId: '1:269333681612:android:efdf0a9739d95ec474f969',
    messagingSenderId: '269333681612',
    projectId: 'woundcare-fyp',
    storageBucket: 'woundcare-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1Zk8iYYIYA51t6A-7nMi4PMf4K1h4tU',
    appId: '1:269333681612:ios:a043306f989cb8ad74f969',
    messagingSenderId: '269333681612',
    projectId: 'woundcare-fyp',
    storageBucket: 'woundcare-fyp.firebasestorage.app',
    iosBundleId: 'com.example.woundcareAiTablet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1Zk8iYYIYA51t6A-7nMi4PMf4K1h4tU',
    appId: '1:269333681612:ios:a043306f989cb8ad74f969',
    messagingSenderId: '269333681612',
    projectId: 'woundcare-fyp',
    storageBucket: 'woundcare-fyp.firebasestorage.app',
    iosBundleId: 'com.example.woundcareAiTablet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodMvLgjcKIlDH3qS7rJ-lrirW65NbN40',
    appId: '1:269333681612:web:262fb059a9fd1fe374f969',
    messagingSenderId: '269333681612',
    projectId: 'woundcare-fyp',
    authDomain: 'woundcare-fyp.firebaseapp.com',
    storageBucket: 'woundcare-fyp.firebasestorage.app',
    measurementId: 'G-VNM8VY7NXM',
  );
}
